name: coproc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.3
  - stable-baselines3=2.1.0
  - mujoco=2.3.7
  - dm-control=1.0.14
  - tqdm=4.66.1
  - wandb=0.15.2
  - tensorboard=2.15.0
  - scipy=1.11.3
  - attrs=23.1.0
  - dill=0.3.7
  - gin-config=0.5.0
  - kornia=0.7.0
  - flatten-dict=0.4.2
  - termcolor=2.3.0
  - sk-video=1.1.10
  - opencv=4.8.1
  - imageio=2.34.0
  - networkx=3.1
  - shimmy=1.3.0
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch
    - gymnasium[mujoco]==0.29.1
    - gymnasium[box2d]==0.29.1
    - gym[mujoco]==0.26.1
