# @package _group_
env: "coproc__LunarLander-v2"
term_fn: "no_termination"

env_cfg:
  _target_: "mbrl.third_party.coprocessors.make"
  gym_env: "LunarLander-v2"
  brain: "sac"
  brain_seed: 0
  pct_lesion: 0.1
  region: null
  env_seed: 0
  injury_seed: 0
  stim_dim: 2
  temporal: false
  brain_obs: false
  data_size: 25

num_steps: 125000
epoch_length: 1000
num_elites: 5
patience: 5
model_lr: 0.001
model_wd: 0.00001
model_batch_size: 256
validation_ratio: 0.2
freq_train_model: 250
effective_model_rollouts_per_step: 400
rollout_schedule: [20, 150, 1, 15]
num_sac_updates_per_step: 40
sac_updates_every_steps: 1
num_epochs_to_retain_sac_buffer: 1

sac_gamma: 0.99
sac_tau: 0.005
sac_alpha: 0.2
sac_policy: "Gaussian"
sac_target_update_interval: 4
sac_automatic_entropy_tuning: false
sac_target_entropy: 1 # ignored, since entropy tuning is false
sac_hidden_size: 512
sac_lr: 0.0003
sac_batch_size: 256